apiVersion: v1
kind: Secret
metadata:
 name: job-creds
type: Opaque
data:
  Rolearn: YXJuOmF3czppYW06OjI3ODk5NjEzNjAwMzpyb2xlL1Jlc3RhdXJhbnQtcHJvamVjdC1kYXRhLXJlYWRlci1yb2xl
  BucketName: cmVzdGF1cmFudC1wcm9qZWN0LWRhdGE=
  host: d3JpdGUtZGItc2VydmljZQ==
  password: bXktcGFzc3dvcmQ=
  user: YWRtaW4=
  dbname: REI=